#### Notes ####
#bindsym --to-code $mod+n exec $sway_source/scripts/notah.sh
bindsym --to-code $mod+n exec /home/radwan/Radwan/Notah/src/linux-menus/notah.sh
bindsym --to-code $mod+m exec /home/radwan/Radwan/Notah/src/linux-menus/notah_browser.sh


#### Apps shortcuts ####
bindsym --to-code $mod+Shift+o exec ~/UserApps/AppImages/Obsidian.AppImage
bindsym --to-code $mod+Shift+a exec brave-browser-stable
