### Startup apps ###

# opening apps with sudo
exec xhost si:localuser:root &

# dbus (for portals)
exec dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP

# XDG Desktop Portal ( screen sharing)
exec /usr/libexec/xdg-desktop-portal-wlr &
exec /usr/libexec/xdg-desktop-portal -r &

# UserServices
exec runsvdir ~/UserServices/sv &

# Sound (PipeWire)
exec pipewire &

# Notifications
exec mako &

# Polkit (Authenticating)
exec /usr/libexec/polkit-gnome-authentication-agent-1 &

# Network Manager
exec nm-applet --indicator &

# Bluetooth
exec blueman-applet &

# Clipboard Manager (Clipman)
exec wl-paste -t text --watch clipman store

# USB Auto-mount
exec udiskie -t &

# SyncThing (you will need to make it a service if you are maling  a server)
exec syncthing --no-browser --logfile=default > /dev/null 2>&1


