# SwayFX Effects
corner_radius 8
smart_corner_radius enable
blur enable
blur_passes 2
blur_radius 5
shadows enable
shadow_blur_radius 20
default_dim_inactive 0.3
#default_dim_inactive 0.1
#for_window [class=".*"] opacity 0.95
#for_window [app_id=".*"] opacity 0.95

# Smart Borders (تكملة للموضوع)
smart_borders on
