# like Graphite black
client.focused          #2a2a2a   #1c1c1c   #e8e8e8   #555555   #3a3a3a
client.focused_inactive #1a1a1a   #1a1a1a   #666666   #1a1a1a   #1a1a1a
client.unfocused        #1a1a1a   #1a1a1a   #444444   #1a1a1a   #1a1a1a
client.urgent           #8b0000   #8b0000   #e8e8e8   #8b0000   #8b0000
