#### Variables ####
set $sway_source $HOME/.config/sway/

#### Bars ####
# Main bar
bar {
    id main_bar
    position bottom
    tray_output none
    font pango:JetBrains Mono 11
    status_command $sway_source/scripts/main_status.sh
}

# Disabling system bar (good for way bad ram status)
bindsym --to-code $mod+Shift+b exec $sway_source/scripts/toggle_second_bar.sh


#### Wallpapers ####
# Random wallpaper on startup
exec $sway_source/scripts/random_wall.sh

# Keybinding to choose wallpaper manually
bindsym --to-code $mod+Shift+w exec $sway_source/scripts/chosen_wall.sh

# Keybinding to choose wallpaper randomly
bindsym --to-code $mod+Shift+r exec $sway_source/scripts/random_wall.sh


#### Control Panel #### 
bindsym --to-code $mod+Shift+s exec $sway_source/scripts/control_panel.sh


#### emojis ####
bindsym --to-code $mod+Shift+i exec $sway_source/scripts/fuzzel-emoji.sh


#### usefulGuard - For battery and usb ports ####
exec $sway_source/scripts/usefulGuard.sh
