#### Variables ####
set $sway_source $HOME/.config/sway/

#### Gaps ###
# enable os disabe sway gaps
bindsym --to-code $mod+Shift+g exec $sway_source/scripts/toggle_gaps.sh

#### usefulGuard - For battery and usb ports ####
exec $sway_source/scripts/usefulGuard.sh
