set $ipc qs -c noctalia-shell ipc call

bindsym --to-code $mod+d exec $ipc launcher toggle
bindsym --to-code $mod+Shift+s exec $ipc controlCenter toggle
bindsym --to-code $mod+comma exec $ipc settings toggle

bindsym --locked XF86AudioRaiseVolume exec $ipc volume increase
bindsym --locked XF86AudioLowerVolume exec $ipc volume decrease
bindsym --locked XF86AudioMute exec $ipc volume muteOutput
bindsym --locked XF86MonBrightnessUp exec $ipc brightness increase
bindsym --locked XF86MonBrightnessDown exec $ipc brightness decrease
