# Second bar
bar {
    id system_bar
    position bottom
    mode hide
    hidden_state hide
#    tray_output none
    font pango:JetBrains Mono 11
    status_command $sway_source/scripts/second_bar.sh
}

# Bar toggling 
bindsym --to-code $mod+b+1 exec swaymsg bar main_bar mode toggle
bindsym --to-code $mod+b+2 exec swaymsg bar system_bar mode toggle 
